name: Tests the S3 action
on: [push]
jobs:
  test-s3:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: test s3 bucket
        uses: ./
        with:
          directories: './test/**'
          access-key: ${{ secrets.S3_ACCESS_KEY }}
          secret-key: ${{ secrets.S3_SECRET_KEY }}
          use-wasabi: 'true'
          bucket: s3-test
